import '../models/app_models.dart';

class MockRepository {
  static final List<Locality> localities = [
    const Locality(id: 'loc_1', name: 'Sector 18', area: 'Atta Market, Wave Mall', city: 'Noida', state: 'Delhi NCR', pincode: '201301', lat: 28.5708, lng: 77.3260, isPopular: true),
    const Locality(id: 'loc_2', name: 'Sector 62', area: 'TechZone, Stellar IT Park', city: 'Noida', state: 'Delhi NCR', pincode: '201309', lat: 28.6280, lng: 77.3649, isPopular: true),
    const Locality(id: 'loc_3', name: 'Indirapuram', area: 'Shipra Sun City, Ahinsa Khand', city: 'Ghaziabad', state: 'Delhi NCR', pincode: '201014', lat: 28.6415, lng: 77.3714, isPopular: true),
    const Locality(id: 'loc_4', name: 'Connaught Place', area: 'Inner Circle, Barakhamba', city: 'New Delhi', state: 'Delhi NCR', pincode: '110001', lat: 28.6304, lng: 77.2177, isPopular: true),
    const Locality(id: 'loc_5', name: 'Cyber City', area: 'DLF Phase 2, Belvedere', city: 'Gurugram', state: 'Delhi NCR', pincode: '122002', lat: 28.4906, lng: 77.0899, isPopular: true),
    const Locality(id: 'loc_6', name: 'Koramangala', area: '4th Block, 80 Feet Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560034', lat: 12.9352, lng: 77.6245, isPopular: true),
    const Locality(id: 'loc_7', name: 'Andheri West', area: 'Lokhandwala Complex', city: 'Mumbai', state: 'Maharashtra', pincode: '400053', lat: 19.1363, lng: 72.8277, isPopular: true),
    const Locality(id: 'loc_8', name: 'Bandra West', area: 'Hill Road, Pali Hill', city: 'Mumbai', state: 'Maharashtra', pincode: '400050', lat: 19.0596, lng: 72.8295, isPopular: true),
    const Locality(id: 'loc_9', name: 'HSR Layout', area: 'Sector 1 & 2, 27th Main', city: 'Bengaluru', state: 'Karnataka', pincode: '560102', lat: 12.9121, lng: 77.6446, isPopular: true),
  ];

  static final List<ServiceCategory> categories = [
    const ServiceCategory(
      id: 'ac',
      name: 'AC Service & Repair',
      nameHi: 'AC सर्विस व रिपेयर',
      icon: '❄️',
      imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80',
      bookingCount: '2.4k+',
      desc: 'Foam jet cleaning, gas check & leak fix',
      startingPrice: 199,
      subServices: [
        SubService(id: 'ac_1', title: 'Deep Foam Jet Service', titleHi: 'पावर जेट डीप क्लीनिंग', price: 499, duration: '45 mins'),
        SubService(id: 'ac_2', title: 'Gas Leak Check & Refill', titleHi: 'गैस लीक जांच व रिफिल', price: 1200, duration: '60 mins'),
        SubService(id: 'ac_3', title: 'Cooling Issue Diagnosis', titleHi: 'कूलिंग न होने की जांच', price: 199, duration: '30 mins'),
        SubService(id: 'ac_4', title: 'AC Installation / Uninstallation', titleHi: 'AC लगाना या हटाना', price: 799, duration: '90 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'plumber',
      name: 'Plumber',
      nameHi: 'प्लंबर',
      icon: '🔧',
      imageUrl: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=400&q=80',
      bookingCount: '1.8k+',
      desc: 'Tap leakage, pipe fittings, drain unblock',
      startingPrice: 149,
      subServices: [
        SubService(id: 'pl_1', title: 'Tap & Mixer Leakage Fix', titleHi: 'नल लीकेज रिपेयर', price: 149, duration: '20 mins'),
        SubService(id: 'pl_2', title: 'Drain Jam Unclogging', titleHi: 'ड्रेन जाम खोलना', price: 299, duration: '35 mins'),
        SubService(id: 'pl_3', title: 'Toilet Jet Spray & Flush Tank', titleHi: 'जेट स्प्रे व फ्लश रिपेयर', price: 199, duration: '30 mins'),
        SubService(id: 'pl_4', title: 'Water Tank Cleaning (1000L)', titleHi: 'पानी की टंकी सफाई', price: 799, duration: '60 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'electrician',
      name: 'Electrician',
      nameHi: 'इलेक्ट्रीशियन',
      icon: '⚡',
      imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=400&q=80',
      bookingCount: '3.1k+',
      desc: 'Wiring, switchboard, fan & MCB repair',
      startingPrice: 199,
      subServices: [
        SubService(id: 'el_1', title: 'Switchboard / Socket Fix', titleHi: 'स्विचबोर्ड रिपेयर', price: 149, duration: '20 mins'),
        SubService(id: 'el_2', title: 'MCB Tripping / Short Circuit', titleHi: 'एमसीबी समस्या', price: 249, duration: '30 mins'),
        SubService(id: 'el_3', title: 'Ceiling Fan Install / Repair', titleHi: 'पंखे की मरम्मत', price: 199, duration: '30 mins'),
        SubService(id: 'el_4', title: 'Inverter & Battery Wiring', titleHi: 'इन्वर्टर वायरिंग', price: 399, duration: '45 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'ro',
      name: 'RO Purifier',
      nameHi: 'RO वाटर प्यूरीफायर',
      icon: '💧',
      imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=400&q=80',
      bookingCount: '980+',
      desc: 'Filter replacement, membrane & TDS tune',
      startingPrice: 99,
      subServices: [
        SubService(id: 'ro_1', title: 'General Service & TDS Check', titleHi: 'सर्विस व टीडीएस जांच', price: 199, duration: '30 mins'),
        SubService(id: 'ro_2', title: 'Complete Filter Kit Change', titleHi: 'फिल्टर किट बदलना', price: 799, duration: '45 mins'),
        SubService(id: 'ro_3', title: 'RO Membrane Replacement', titleHi: 'मेम्ब्रेन बदलना', price: 999, duration: '45 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'fridge',
      name: 'Refrigerator',
      nameHi: 'फ्रिज रिपेयर',
      icon: '🧊',
      imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=400&q=80',
      bookingCount: '1.2k+',
      desc: 'Cooling issues, compressor & gas recharge',
      startingPrice: 199,
      subServices: [
        SubService(id: 'fr_1', title: 'Diagnosis & Inspection', titleHi: 'जांच व निरीक्षण', price: 199, duration: '30 mins'),
        SubService(id: 'fr_2', title: 'Compressor Gas Refill', titleHi: 'गैस रिफिल', price: 1299, duration: '60 mins'),
        SubService(id: 'fr_3', title: 'Thermostat / Defrost Fix', titleHi: 'थर्मोस्टेट रिपेयर', price: 449, duration: '40 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'washing',
      name: 'Washing Machine',
      nameHi: 'वाशिंग मशीन',
      icon: '🌀',
      imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=400&q=80',
      bookingCount: '1.5k+',
      desc: 'Motor, drum vibration & drain pump fix',
      startingPrice: 199,
      subServices: [
        SubService(id: 'wm_1', title: 'Spin / Drain Issue Check', titleHi: 'स्पिन / ड्रेन समस्या', price: 199, duration: '35 mins'),
        SubService(id: 'wm_2', title: 'Motor & Belt Replacement', titleHi: 'मोटर व बेल्ट बदलना', price: 699, duration: '50 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'geyser',
      name: 'Geyser & Heater',
      nameHi: 'गीज़र रिपेयर',
      icon: '♨️',
      imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=400&q=80',
      bookingCount: '870+',
      desc: 'Heating element, thermostat & leak fix',
      startingPrice: 199,
      subServices: [
        SubService(id: 'gy_1', title: 'Heating Element Change', titleHi: 'हीटिंग एलिमेंट बदलना', price: 499, duration: '40 mins'),
        SubService(id: 'gy_2', title: 'Geyser Leakage & Descaling', titleHi: 'गीज़र लीकेज रिपेयर', price: 349, duration: '35 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'chimney',
      name: 'Kitchen Chimney',
      nameHi: 'किचन चिमनी',
      icon: '🍳',
      imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=400&q=80',
      bookingCount: '720+',
      desc: 'Deep degreasing, carbon filter, motor repair',
      startingPrice: 399,
      subServices: [
        SubService(id: 'ch_1', title: 'Chemical Deep Cleaning', titleHi: 'चिमनी डीप क्लीनिंग', price: 599, duration: '60 mins'),
        SubService(id: 'ch_2', title: 'Duct Pipe Installation', titleHi: 'डक्ट पाइप फिटिंग', price: 499, duration: '45 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'carpenter',
      name: 'Carpenter',
      nameHi: 'बढ़ई',
      icon: '🔨',
      imageUrl: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=400&q=80',
      bookingCount: '890+',
      desc: 'Door lock, hinge, furniture assembly',
      startingPrice: 249,
      subServices: [
        SubService(id: 'cp_1', title: 'Door Lock Installation', titleHi: 'ताला लगाना', price: 249, duration: '30 mins'),
        SubService(id: 'cp_2', title: 'Modular Kitchen Hinge Fix', titleHi: 'कब्जे व चैनल रिपेयर', price: 299, duration: '35 mins'),
        SubService(id: 'cp_3', title: 'Bed / Furniture Repair', titleHi: 'बेड व फर्नीचर रिपेयर', price: 449, duration: '60 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'painter',
      name: 'Painter',
      nameHi: 'पेंटर व वाटरप्रूफिंग',
      icon: '🎨',
      imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=400&q=80',
      bookingCount: '650+',
      desc: 'Room repainting, touchup & waterproofing',
      startingPrice: 299,
      subServices: [
        SubService(id: 'pt_1', title: 'Single Wall Touchup', titleHi: 'वॉल टचअप', price: 499, duration: '60 mins'),
        SubService(id: 'pt_2', title: 'Wall Seepage Waterproofing', titleHi: 'सीलन वाटरप्रूफिंग', price: 899, duration: '90 mins'),
        SubService(id: 'pt_3', title: 'Complete Room Fresh Paint', titleHi: 'कमरा पेंटिंग', price: 1899, duration: '1 day'),
      ],
    ),
    const ServiceCategory(
      id: 'cleaner',
      name: 'Deep Cleaning',
      nameHi: 'डीप क्लीनिंग',
      icon: '✨',
      imageUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=400&q=80',
      bookingCount: '2.0k+',
      desc: 'Bathroom scrubbing, kitchen & full home',
      startingPrice: 399,
      subServices: [
        SubService(id: 'cl_1', title: 'Mechanized Bathroom Scrub', titleHi: 'बाथरूम डीप क्लीन', price: 399, duration: '45 mins'),
        SubService(id: 'cl_2', title: 'Sofa & Mattress Shampoo', titleHi: 'सोफा शैम्पू वॉश', price: 699, duration: '60 mins'),
        SubService(id: 'cl_3', title: 'Full 2BHK Deep Home Clean', titleHi: 'पूरे घर की डीप सफाई', price: 2499, duration: '4 hours'),
      ],
    ),
    const ServiceCategory(
      id: 'pest',
      name: 'Pest Control',
      nameHi: 'पेस्ट कंट्रोल',
      icon: '🛡️',
      imageUrl: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&w=400&q=80',
      bookingCount: '760+',
      desc: 'Odorless cockroach, termite & bed bug control',
      startingPrice: 599,
      subServices: [
        SubService(id: 'ps_1', title: 'Cockroach Herbal Gel Control', titleHi: 'कॉकरोच हर्बल जेल', price: 599, duration: '45 mins'),
        SubService(id: 'ps_2', title: 'Termite Anti-Wood Drill Fix', titleHi: 'दीमक नियंत्रण', price: 1299, duration: '90 mins'),
      ],
    ),
  ];

  static final List<WorkerProfile> workers = [
    const WorkerProfile(
      id: 'w1',
      name: 'Ramesh Kumar',
      avatar: 'RK',
      category: 'AC Expert',
      skills: ['Foam Jet Wash', 'Gas Charging', 'PCB Diagnostics'],
      bio: 'Specialized in split & window AC. 7 years experience. Police verified with 90-day warranty.',
      experienceYears: '7 years',
      rating: 4.9,
      totalReviews: 847,
      jobsCompleted: 847,
      onTimeRate: 99.1,
      completionRate: 98.6,
      responseTime: '3 min',
      visitFee: 199,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      distance: '0.8 km',
      serviceAreas: 'Sector 18, 62, Indirapuram',
    ),
    const WorkerProfile(
      id: 'w2',
      name: 'Sunil Yadav',
      avatar: 'SY',
      category: 'Plumber',
      skills: ['Leakage Repair', 'Drain Cleaning', 'Mixer Installation'],
      bio: 'Master plumber with 5 years experience in high-rise societies.',
      experienceYears: '5 years',
      rating: 4.7,
      totalReviews: 612,
      jobsCompleted: 612,
      onTimeRate: 96.0,
      completionRate: 97.4,
      responseTime: '4 min',
      visitFee: 149,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      distance: '1.2 km',
      serviceAreas: 'Noida & Ghaziabad',
    ),
    const WorkerProfile(
      id: 'w3',
      name: 'Amit Singh',
      avatar: 'AS',
      category: 'Electrician',
      skills: ['Short Circuit', 'Concealed Wiring', 'Smart MCB'],
      bio: 'Licensed electrician with 9 years background.',
      experienceYears: '9 years',
      rating: 4.8,
      totalReviews: 1204,
      jobsCompleted: 1204,
      onTimeRate: 97.0,
      completionRate: 99.0,
      responseTime: '5 min',
      visitFee: 199,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      distance: '0.5 km',
      serviceAreas: 'All Noida',
    ),
  ];

  static final List<BankAccount> defaultBankAccounts = [
    const BankAccount(
      id: 'bnk_1',
      bankName: 'HDFC Bank Ltd.',
      accountNumber: '50100492817291',
      ifscCode: 'HDFC0001202',
      holderName: 'Ankit Verma',
      isPrimary: true,
    ),
  ];

  static final List<SavedUpi> defaultSavedUpis = [
    const SavedUpi(
      id: 'upi_1',
      upiId: '9876543210@paytm',
      provider: 'Paytm UPI',
      isDefault: true,
    ),
    const SavedUpi(
      id: 'upi_2',
      upiId: 'ankitverma@okhdfcbank',
      provider: 'Google Pay',
      isDefault: false,
    ),
  ];

  static final List<FaqItem> faqs = [
    const FaqItem(
      id: 'faq_1',
      question: 'How does KaamWala First-Pickup (Uber/Ola Style) work?',
      answer: 'When you create a service request, it is instantly broadcasted to verified pros within 3km. The first technician to tap accept gets the job via an atomic lock. There is no quote comparison, bidding, or bargaining delay.',
      category: 'Booking',
    ),
    const FaqItem(
      id: 'faq_2',
      question: 'What is the ₹199 Visit Fee & Inspection Approval Gate?',
      answer: 'The ₹199 fee covers doorstep visit, diagnostic testing, and travel. After inspecting your appliance, the pro shares a transparent estimate on your phone. Work only starts after you tap "Approve Estimate" in the app, preventing bill shock.',
      category: 'Pricing',
    ),
    const FaqItem(
      id: 'faq_3',
      question: 'What is the KaamWala 30-Day Doorstep Guarantee?',
      answer: 'All services are backed by a 30-day warranty. If the same issue reoccurs within 30 days of completion, our pro will revisit and resolve it free of charge.',
      category: 'Safety',
    ),
    const FaqItem(
      id: 'faq_4',
      question: 'How does Phone Masking protect my privacy?',
      answer: 'When you call your assigned technician, our virtual relay (+91 1800 890 4128) bridges the call without exposing your personal phone number to the worker.',
      category: 'Privacy',
    ),
    const FaqItem(
      id: 'faq_5',
      question: 'How does Wallet Cashback & Refer & Earn work?',
      answer: 'You earn flat ₹100 in your KaamWala Wallet whenever a friend uses your referral code. Wallet balance can be applied for 1-tap discounts on any doorstep service bill.',
      category: 'Wallet',
    ),
    const FaqItem(
      id: 'faq_6',
      question: 'Can I cancel or reschedule my booking?',
      answer: 'Yes! You can reschedule your time slot anytime from the Bookings tab or cancel before the technician arrives at your doorstep with zero penalty.',
      category: 'Booking',
    ),
  ];

  static CustomerJob createInitialActiveJob() {
    return CustomerJob(
      id: 'KW-28491',
      category: 'ac',
      serviceName: 'AC Service & Repair',
      description: 'AC not cooling properly with water dripping from indoor unit.',
      address: 'Sector 18, Noida • 201301',
      date: 'Today',
      time: '3:00 PM - 5:00 PM',
      status: 'ON_THE_WAY',
      visitFee: 199,
      estimatedAmount: 1200,
      finalAmount: 1399,
      assignedWorker: workers.first,
      arrivalEta: '12 min',
      isInspectionApproved: false,
      isCompletedConfirmed: false,
    );
  }

  static List<NotificationItem> getNotifications() {
    return const [
      NotificationItem(
        id: 'n1',
        title: 'Worker is on the way • ETA 12 min',
        subtitle: 'Ramesh Kumar • KW-28491 • Track live on GPS',
        time: '2m ago',
        isRead: false,
        type: 'worker',
      ),
      NotificationItem(
        id: 'n2',
        title: 'Request posted • Ramesh Kumar accepted first',
        subtitle: 'KW-28491 • Auto-assigned to nearest top-rated pro',
        time: '14m ago',
        isRead: false,
        type: 'worker',
      ),
      NotificationItem(
        id: 'n3',
        title: 'AC Maintenance Reminder',
        subtitle: 'Monsoon Care plan available • Save flat 30%',
        time: '1d ago',
        isRead: true,
        type: 'promo',
      ),
      NotificationItem(
        id: 'n4',
        title: 'Payment success • Invoice ready',
        subtitle: 'KW-28310 • ₹650 • GST Invoice downloaded',
        time: '2d ago',
        isRead: true,
        type: 'wallet',
      ),
    ];
  }
}
