import '../models/app_models.dart';

class MockRepository {
  static final List<Locality> localities = [
    const Locality(id: 'loc_1', name: 'Sector 18', area: 'Atta Market, Wave Mall', city: 'Noida', state: 'Delhi NCR', pincode: '201301', lat: 28.5708, lng: 77.3260, isPopular: true),
    const Locality(id: 'loc_2', name: 'Sector 62', area: 'TechZone, Stellar IT Park', city: 'Noida', state: 'Delhi NCR', pincode: '201309', lat: 28.6280, lng: 77.3649, isPopular: true),
    const Locality(id: 'loc_3', name: 'Indirapuram', area: 'Shipra Sun City, Ahinsa Khand', city: 'Ghaziabad', state: 'Delhi NCR', pincode: '201014', lat: 28.6415, lng: 77.3714, isPopular: true),
    const Locality(id: 'loc_4', name: 'Connaught Place', area: 'Inner Circle, Barakhamba', city: 'New Delhi', state: 'Delhi NCR', pincode: '110001', lat: 28.6304, lng: 77.2177, isPopular: true),
    const Locality(id: 'loc_5', name: 'Cyber City', area: 'DLF Phase 2, Belvedere', city: 'Gurugram', state: 'Delhi NCR', pincode: '122002', lat: 28.4906, lng: 77.0899, isPopular: true),
    const Locality(id: 'loc_6', name: 'Koramangala', area: '4th Block, 80 Feet Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560034', lat: 12.9352, lng: 77.6245, isPopular: true),
    const Locality(id: 'loc_7', name: 'Andheri West', area: 'Lokhandwala Complex', city: 'Mumbai', state: 'Maharashtra', pincode: '400053', lat: 19.1363, lng: 72.8277, isPopular: true),
    const Locality(id: 'loc_8', name: 'Bandra West', area: 'Hill Road, Pali Hill', city: 'Mumbai', state: 'Maharashtra', pincode: '400050', lat: 19.0596, lng: 72.8295, isPopular: true),
    const Locality(id: 'loc_9', name: 'HSR Layout', area: 'Sector 1 & 2, 27th Main', city: 'Bengaluru', state: 'Karnataka', pincode: '560102', lat: 12.9121, lng: 77.6446, isPopular: true),
  ];

  static final List<ServiceCategory> categories = [
    const ServiceCategory(
      id: 'ac',
      name: 'AC Service',
      nameHi: 'AC सर्विस',
      icon: '❄️',
      bookingCount: '2.4k+',
      desc: 'Foam jet cleaning, gas check & leak fix',
      startingPrice: 199,
      subServices: [
        SubService(id: 'ac_1', title: 'Deep Foam Jet Service', titleHi: 'पावर जेट डीप क्लीनिंग', price: 499, duration: '45 mins'),
        SubService(id: 'ac_2', title: 'Gas Leak Check & Refill', titleHi: 'गैस लीक जांच व रिफिल', price: 1200, duration: '60 mins'),
        SubService(id: 'ac_3', title: 'Cooling Issue Diagnosis', titleHi: 'कूलिंग न होने की जांच', price: 199, duration: '30 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'plumber',
      name: 'Plumber',
      nameHi: 'प्लंबर',
      icon: '🔧',
      bookingCount: '1.8k+',
      desc: 'Tap leakage, pipe fittings, drain unblock',
      startingPrice: 149,
      subServices: [
        SubService(id: 'pl_1', title: 'Tap & Mixer Leakage', titleHi: 'नल लीकेज रिपेयर', price: 149, duration: '20 mins'),
        SubService(id: 'pl_2', title: 'Drain Jam Unclogging', titleHi: 'ड्रेन जाम खोलना', price: 299, duration: '35 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'electrician',
      name: 'Electrician',
      nameHi: 'इलेक्ट्रीशियन',
      icon: '⚡',
      bookingCount: '3.1k+',
      desc: 'Wiring, switchboard, fan & MCB repair',
      startingPrice: 199,
      subServices: [
        SubService(id: 'el_1', title: 'Switchboard / Socket Fix', titleHi: 'स्विचबोर्ड रिपेयर', price: 149, duration: '20 mins'),
        SubService(id: 'el_2', title: 'MCB / Tripping Fix', titleHi: 'एमसीबी समस्या', price: 249, duration: '30 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'ro',
      name: 'RO Repair',
      nameHi: 'RO रिपेयर',
      icon: '💧',
      bookingCount: '980+',
      desc: 'Filter replacement, membrane & TDS tune',
      startingPrice: 99,
      subServices: [
        SubService(id: 'ro_1', title: 'General Service & TDS Check', titleHi: 'सर्विस व टीडीएस जांच', price: 199, duration: '30 mins'),
        SubService(id: 'ro_2', title: 'Complete Filter Kit Change', titleHi: 'फिल्टर किट बदलना', price: 799, duration: '45 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'fridge',
      name: 'Refrigerator',
      nameHi: 'फ्रिज',
      icon: '🧊',
      bookingCount: '1.2k+',
      desc: 'Cooling issues, compressor & gas recharge',
      startingPrice: 199,
      subServices: [
        SubService(id: 'fr_1', title: 'Diagnosis & Inspection', titleHi: 'जांच व निरीक्षण', price: 199, duration: '30 mins'),
        SubService(id: 'fr_2', title: 'Compressor Gas Refill', titleHi: 'गैस रिफिल', price: 1299, duration: '60 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'washing',
      name: 'Washing M/C',
      nameHi: 'वाशिंग मशीन',
      icon: '🌀',
      bookingCount: '1.5k+',
      desc: 'Motor, drum vibration & drain pump fix',
      startingPrice: 199,
      subServices: [
        SubService(id: 'wm_1', title: 'Spin / Drain Issue Check', titleHi: 'स्पिन / ड्रेन समस्या', price: 199, duration: '35 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'carpenter',
      name: 'Carpenter',
      nameHi: 'बढ़ई',
      icon: '🔨',
      bookingCount: '890+',
      desc: 'Door lock, hinge, furniture assembly',
      startingPrice: 249,
      subServices: [
        SubService(id: 'cp_1', title: 'Door Lock Installation', titleHi: 'ताला लगाना', price: 249, duration: '30 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'painter',
      name: 'Painter',
      nameHi: 'पेंटर',
      icon: '🎨',
      bookingCount: '650+',
      desc: 'Room repainting, touchup & waterproofing',
      startingPrice: 299,
      subServices: [
        SubService(id: 'pt_1', title: 'Single Wall Touchup', titleHi: 'वॉल टचअप', price: 499, duration: '60 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'cleaner',
      name: 'Deep Clean',
      nameHi: 'सफाई',
      icon: '✨',
      bookingCount: '2.0k+',
      desc: 'Bathroom scrubbing, kitchen & full home',
      startingPrice: 399,
      subServices: [
        SubService(id: 'cl_1', title: 'Mechanized Bathroom Scrub', titleHi: 'बाथरूम डीप क्लीन', price: 399, duration: '45 mins'),
      ],
    ),
  ];

  static final List<WorkerProfile> workers = [
    const WorkerProfile(
      id: 'w1',
      name: 'Ramesh Kumar',
      avatar: 'RK',
      category: 'AC Expert',
      skills: ['Foam Jet Wash', 'Gas Charging', 'PCB Diagnostics'],
      bio: 'Specialized in split & window AC. 7 years experience. Police verified with 90-day warranty.',
      experienceYears: '7 years',
      rating: 4.9,
      totalReviews: 847,
      jobsCompleted: 847,
      onTimeRate: 96.0,
      completionRate: 98.0,
      responseTime: '8 min',
      visitFee: 199,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      distance: '0.8 km',
      serviceAreas: 'Sector 18-27 Noida, Indirapuram',
    ),
    const WorkerProfile(
      id: 'w2',
      name: 'Sunil Yadav',
      avatar: 'SY',
      category: 'Plumber',
      skills: ['Concealed Leakage', 'Pipe Fittings', 'Mixer Repair'],
      bio: 'Experienced plumber with genuine CPVC tools and fittings.',
      experienceYears: '5 years',
      rating: 4.7,
      totalReviews: 523,
      jobsCompleted: 523,
      onTimeRate: 92.0,
      completionRate: 95.0,
      responseTime: '15 min',
      visitFee: 149,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: false,
      isFastResponder: false,
      distance: '1.2 km',
      serviceAreas: 'Noida, Vaishali',
    ),
    const WorkerProfile(
      id: 'w3',
      name: 'Amit Singh',
      avatar: 'AS',
      category: 'Electrician',
      skills: ['Short Circuit', 'Concealed Wiring', 'Smart MCB'],
      bio: 'Licensed electrician with 9 years background.',
      experienceYears: '9 years',
      rating: 4.8,
      totalReviews: 1204,
      jobsCompleted: 1204,
      onTimeRate: 97.0,
      completionRate: 99.0,
      responseTime: '5 min',
      visitFee: 199,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      distance: '0.5 km',
      serviceAreas: 'All Noida',
    ),
  ];

  static CustomerJob createInitialActiveJob() {
    return CustomerJob(
      id: 'KW-28491',
      category: 'ac',
      serviceName: 'AC Service & Repair',
      description: 'AC not cooling properly with water dripping from indoor unit.',
      address: 'Sector 18, Noida • 201301',
      date: 'Today',
      time: '3:00 PM - 5:00 PM',
      status: 'ON_THE_WAY',
      visitFee: 199,
      estimatedAmount: 1200,
      finalAmount: 1399,
      assignedWorker: workers.first,
      arrivalEta: '12 min',
      isInspectionApproved: false,
      isCompletedConfirmed: false,
    );
  }

  static List<NotificationItem> getNotifications() {
    return const [
      NotificationItem(
        id: 'n1',
        title: 'Worker is on the way • ETA 12 min',
        subtitle: 'Ramesh Kumar • KW-28491 • Track live on GPS',
        time: '2m ago',
        isRead: false,
        type: 'worker',
      ),
      NotificationItem(
        id: 'n2',
        title: 'Request posted • Ramesh Kumar accepted first',
        subtitle: 'KW-28491 • Auto-assigned to nearest top-rated pro',
        time: '14m ago',
        isRead: false,
        type: 'worker',
      ),
      NotificationItem(
        id: 'n3',
        title: 'AC Maintenance Reminder',
        subtitle: 'Monsoon Care plan available • Save flat 30%',
        time: '1d ago',
        isRead: true,
        type: 'promo',
      ),
      NotificationItem(
        id: 'n4',
        title: 'Payment success • Invoice ready',
        subtitle: 'KW-28310 • ₹650 • GST Invoice downloaded',
        time: '2d ago',
        isRead: true,
        type: 'wallet',
      ),
    ];
  }
}
