import '../models/app_models.dart';

class MockRepository {
  static final List<Locality> localities = [
    const Locality(id: 'l1', name: 'Indirapuram', area: 'Shipra Sun City, Ahinsa Khand', city: 'Ghaziabad', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l2', name: 'Sector 62', area: 'TechZone, Stellar IT Park', city: 'Noida', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l3', name: 'Sector 18', area: 'Atta Market, Wave Mall', city: 'Noida', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l4', name: 'Connaught Place', area: 'Inner Circle, Barakhamba', city: 'New Delhi', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l5', name: 'Saket', area: 'Select Citywalk, Press Enclave', city: 'South Delhi', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l6', name: 'DLF Phase 5', area: 'Golf Course Road', city: 'Gurugram', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l7', name: 'Cyber City', area: 'DLF Phase 2, Belvedere', city: 'Gurugram', state: 'Delhi NCR', isPopular: true),
    const Locality(id: 'l8', name: 'Koramangala', area: '4th Block, 80 Feet Road', city: 'Bengaluru', state: 'Karnataka', isPopular: true),
    const Locality(id: 'l9', name: 'HSR Layout', area: 'Sector 1 & 2, 27th Main', city: 'Bengaluru', state: 'Karnataka', isPopular: true),
    const Locality(id: 'l10', name: 'Indiranagar', area: '100ft Road, 12th Main', city: 'Bengaluru', state: 'Karnataka', isPopular: true),
    const Locality(id: 'l11', name: 'Whitefield', area: 'ITPB, Hope Farm', city: 'Bengaluru', state: 'Karnataka', isPopular: true),
    const Locality(id: 'l12', name: 'Andheri West', area: 'Lokhandwala Complex', city: 'Mumbai', state: 'Maharashtra', isPopular: true),
    const Locality(id: 'l13', name: 'Bandra West', area: 'Hill Road, Pali Hill', city: 'Mumbai', state: 'Maharashtra', isPopular: true),
    const Locality(id: 'l14', name: 'Powai', area: 'Hiranandani Gardens', city: 'Mumbai', state: 'Maharashtra', isPopular: true),
    const Locality(id: 'l15', name: 'Banjara Hills', area: 'Road No. 12', city: 'Hyderabad', state: 'Telangana', isPopular: true),
    const Locality(id: 'l16', name: 'Viman Nagar', area: 'Phoenix Marketcity', city: 'Pune', state: 'Maharashtra', isPopular: true),
  ];

  static final List<ServiceCategory> categories = [
    const ServiceCategory(
      id: 'AC',
      name: 'AC Repair & Service',
      nameHi: 'एसी रिपेयर एवं सर्विस',
      icon: '❄️',
      badge: 'Popular',
      desc: 'Foam jet cleaning, gas leak fix & PCB repair',
      startingPrice: 199,
      subServices: [
        SubService(id: 'ac1', title: 'Deep Power Jet Cleaning', titleHi: 'पावर जेट डीप क्लीनिंग', price: 499, duration: '45 mins'),
        SubService(id: 'ac2', title: 'Gas Leak Check & Refill', titleHi: 'गैस लीक जांच व रिफिल', price: 1499, duration: '60 mins'),
        SubService(id: 'ac3', title: 'Installation / Unmounting', titleHi: 'इंस्टॉलेशन / अनइंस्टॉलेशन', price: 799, duration: '90 mins'),
        SubService(id: 'ac4', title: 'Cooling Diagnosis Check', titleHi: 'कूलिंग न होने की जांच', price: 199, duration: '30 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'Electrician',
      name: 'Electrician',
      nameHi: 'इलेक्ट्रीशियन',
      icon: '⚡',
      badge: '15m Fast',
      desc: 'Wiring, MCB tripping, fans, switchboards',
      startingPrice: 149,
      subServices: [
        SubService(id: 'el1', title: 'Switchboard / Socket Fix', titleHi: 'स्विचबोर्ड रिपेयर', price: 149, duration: '20 mins'),
        SubService(id: 'el2', title: 'MCB / Fuse Tripping Fix', titleHi: 'एमसीबी ट्रिपिंग समस्या', price: 249, duration: '30 mins'),
        SubService(id: 'el3', title: 'Ceiling Fan Installation', titleHi: 'पंखा लगाना', price: 199, duration: '35 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'Plumber',
      name: 'Plumber',
      nameHi: 'प्लम्बर',
      icon: '🔧',
      badge: 'Verified',
      desc: 'Tap leakages, pipe blockages & fittings',
      startingPrice: 149,
      subServices: [
        SubService(id: 'pl1', title: 'Tap & Mixer Leakage Repair', titleHi: 'नल / मिक्सर लीकेज', price: 149, duration: '25 mins'),
        SubService(id: 'pl2', title: 'Drain Unclogging', titleHi: 'ड्रेन जाम खोलना', price: 299, duration: '40 mins'),
        SubService(id: 'pl3', title: 'Concealed Pipe Leak Detection', titleHi: 'पाइप लीकेज जांच', price: 499, duration: '60 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'RO',
      name: 'RO Purifier',
      nameHi: 'आर.ओ. प्यूरीफायर',
      icon: '💧',
      badge: 'Top Rated',
      desc: 'Filter replacement, membrane & TDS tune',
      startingPrice: 149,
      subServices: [
        SubService(id: 'ro1', title: 'RO General Service & TDS Test', titleHi: 'आर.ओ. सर्विस व टीडीएस', price: 249, duration: '30 mins'),
        SubService(id: 'ro2', title: 'Complete Filter Kit Change', titleHi: 'फिल्टर किट बदलना', price: 799, duration: '45 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'Refrigerator',
      name: 'Refrigerator',
      nameHi: 'फ्रिज रिपेयर',
      icon: '🧊',
      badge: 'Warranty',
      desc: 'Cooling issue, compressor & gas charge',
      startingPrice: 199,
      subServices: [
        SubService(id: 'fr1', title: 'Not Cooling Diagnostics', titleHi: 'कूलिंग न होने की जांच', price: 199, duration: '30 mins'),
        SubService(id: 'fr2', title: 'Fridge Gas Refill', titleHi: 'गैस रिफिल', price: 1399, duration: '60 mins'),
      ],
    ),
    const ServiceCategory(
      id: 'Cleaner',
      name: 'Deep Cleaning',
      nameHi: 'डीप क्लीनिंग',
      icon: '✨',
      badge: 'Eco Clean',
      desc: 'Bathroom scrubbing, kitchen & full flat',
      startingPrice: 299,
      subServices: [
        SubService(id: 'cl1', title: 'Mechanized Bathroom Clean', titleHi: 'बाथरूम डीप क्लीनिंग', price: 399, duration: '60 mins'),
        SubService(id: 'cl2', title: 'Kitchen & Chimney Degreasing', titleHi: 'किचन सफाई', price: 699, duration: '90 mins'),
      ],
    ),
  ];

  static final List<WorkerProfile> workers = [
    const WorkerProfile(
      id: 'w1',
      name: 'Manoj Kumar Verma',
      category: 'AC',
      skills: ['Jet Foam Cleaning', 'Gas Refill', 'Capacitor & PCB'],
      bio: 'Certified HVAC technician with 8+ years experience. Genuine spares guaranteed.',
      experienceYears: 8,
      rating: 4.9,
      totalReviews: 142,
      jobsCompleted: 310,
      onTimeRate: 99,
      responseTime: '10m',
      visitFee: 199,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      photoUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=300&q=80',
      serviceAreas: 'Indirapuram, Sector 62 Noida, Vaishali',
    ),
    const WorkerProfile(
      id: 'w2',
      name: 'Rajesh Prajapati',
      category: 'Electrician',
      skills: ['MCB Tripping', 'Concealed Wiring', 'Smart Switches'],
      bio: 'Licensed electrician with 10 years experience. Safety first wiring.',
      experienceYears: 10,
      rating: 4.85,
      totalReviews: 98,
      jobsCompleted: 240,
      onTimeRate: 98,
      responseTime: '12m',
      visitFee: 149,
      isIdentityVerified: true,
      isSkillVerified: true,
      isTopRated: true,
      isFastResponder: true,
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      serviceAreas: 'Noida, East Delhi, Indirapuram',
    ),
  ];

  static CustomerJob createInitialJob() {
    return CustomerJob(
      id: 'KW-904128',
      category: 'AC',
      serviceName: 'Split AC Deep Cleaning & Cooling',
      description: 'AC blowing lukewarm air with rattling vibration sound at higher fan speed.',
      address: 'Flat 402, Shipra Sun City, Indirapuram, Ghaziabad',
      date: 'Tomorrow (Fri)',
      time: '10:00 AM - 12:00 PM',
      status: 'QUOTATIONS_RECEIVED',
      visitFee: 199,
      estimatedAmount: 699,
      finalAmount: 699,
      quotes: [
        const Quote(
          id: 'q1',
          workerId: 'w1',
          workerName: 'Manoj Kumar Verma',
          workerRating: 4.9,
          workerJobs: 310,
          workerPhoto: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=300&q=80',
          visitFee: 199,
          estimateMin: 499,
          estimateMax: 799,
          partsExtra: true,
          message: 'Namaste ji! Available with foam jet wash equipment. 30-day warranty.',
          arrivalTime: 'Can reach in 30 mins',
        ),
        const Quote(
          id: 'q2',
          workerId: 'w2',
          workerName: 'Rajesh Prajapati',
          workerRating: 4.85,
          workerJobs: 240,
          workerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
          visitFee: 149,
          estimateMin: 450,
          estimateMax: 850,
          partsExtra: true,
          message: 'AC electrical & vibration specialist. Inspection fee adjusted on work.',
          arrivalTime: 'Available at 11:00 AM',
        ),
      ],
    );
  }
}
